name: Build with CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        # TODO: Fix minor stuff on other OSes
        #os: [ubuntu-latest, windows-latest, macos-latest]
        os: [windows-latest]
        #include:
        #- os: ubuntu-latest
        #  install-deps: |
        #    sudo apt-get update -y
        #    sudo apt-get install -y xorg-dev
        
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      if: ${{ matrix.install-deps }}
      run: ${{ matrix.install-deps }}
      
    - name: Configure CMake
      run: cmake -S . -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install/MesoGen

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Install
      run: cmake --install ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-${{ matrix.os }}
        path: ${{github.workspace}}/install/MesoGen
